name: Auto Update README - credly badges

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-readme:
    name: Update Readme with Badges
    runs-on: ubuntu-latest

    steps:
      - name: Badhes - Readme
        uses: pemtajo/badge-readme@master
          CREDLY_USER:lalit-vatsal
          
