# This is a basic workflow to help you get started with Actions

name: Update Credly Badges and Recent Blog Posts

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # run at 11 PM UTC
    - cron: "0 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-readme:
    name: Update README with Badges
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Badges README
        uses: pemtajo/badge-readme@master
        with:
          CREDLY_USER: "lalit-vatsal"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Blog Posts README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/lprakashv, https://medium.com/feed/@lprakashv"
